# Generated by Django 3.2.4 on 2021-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklogs',
            name='checkback',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklogs',
            name='issue_day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
