# Generated by Django 3.2.4 on 2021-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklogs',
            name='Transaction',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
