# Generated by Django 3.2.4 on 2021-07-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookType',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='bookmodel',
            old_name='book_type',
            new_name='Book_categories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='book_type',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='bookinventry',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='bookinventry',
            name='book_uniqueid',
            field=models.CharField(default='0000000', max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinventry',
            name='book',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, related_name='Book_detail', to='suser.bookmodel'),
            preserve_default=False,
        ),
    ]
