# Generated by Django 3.2.4 on 2021-07-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='getting_report',
        ),
    ]
