# Generated by Django 3.2.4 on 2021-07-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0002_auto_20210706_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklogs',
            name='fine_fee',
        ),
    ]
