# Generated by Django 3.2.4 on 2021-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
