# Generated by Django 3.2.4 on 2021-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0003_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='desgination',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reports_to',
        ),
        migrations.AddField(
            model_name='user',
            name='Student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
